#!/usr/bin/env python
# coding=utf-8
"""Score images generated by test_generate.py with the pretrained classifiers.

    python evaluate.py --images_dir outputs/dit/gen_seed_1/dit_weights/seed_42/count_100000/<run>/guidance_scale1.0_condition_scale1.0
    python evaluate.py --images_dir .../position_composition1_10000/<run>/guidance_scale1.0_condition_scale1.0/images --checkpoint_filter best_model

Reads <images_dir>/<checkpoint>/prompt_key_<key>_sample_<n>.png, infers the test_mode from the path and
reports, per checkpoint:
  - accuracy / confidence / per-label accuracy of the task classifier (count, position or attribute)
  - colour accuracy and joint accuracy for composition runs, shape accuracy and joint accuracy for attribute runs
  - for composition runs the same metrics split into held-out (OOD) and in-distribution label pairs
Results are printed and written to <images_dir>/../evaluation/<name>.json and .csv (plus confusion matrices as CSV).
"""
import argparse
import csv
import json
import os
import re
from collections import defaultdict

import torch
import tqdm
from PIL import Image
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms as T

from data import COLOR_DICT, held_out_pairs
from utils import is_complex, is_composition, load_classifiers, task_of

COLOR_NAMES = list(COLOR_DICT.keys())
FILENAME_RE = re.compile(r"prompt_key_(?P<key>.+)_sample_(?P<n>\d+)\.png$")


def parse_args():
    parser = argparse.ArgumentParser(description="Evaluate generated images with the pretrained classifiers.")
    parser.add_argument("--images_dir", type=str, required=True,
                        help="The images/ folder written by test_generate.py, or its parent (guidance_scale... folder).")
    parser.add_argument("--checkpoint_filter", type=str, default=None,
                        help="Evaluate only this checkpoint: a step number, '-1' for the latest step, or 'best_model'. Default: all.")
    parser.add_argument("--batch_size", type=int, default=256)
    parser.add_argument("--num_workers", type=int, default=4)
    parser.add_argument("--resolution", type=int, default=128, help="Classifier input resolution.")
    parser.add_argument("--device", type=str, default=None)
    parser.add_argument("--save_name", type=str, default="evaluation", help="Base name of the result files.")
    parser.add_argument("--no_save", action="store_true", help="Only print, do not write result files.")
    return parser.parse_args()


# ---------------------------------------------------------------------------
# paths and labels
# ---------------------------------------------------------------------------
def resolve_images_dir(path):
    """Accept the images/ folder or any parent of it (run dir, test_mode dir, ...): descend through
    unique sub-folders until images/ is found, like test_generate.py does for --model_dir."""
    path = path.rstrip("/")
    if not os.path.isdir(path):
        raise FileNotFoundError(f"{path} does not exist")
    current = path
    while os.path.basename(current) != "images":
        if os.path.isdir(os.path.join(current, "images")):
            current = os.path.join(current, "images")
            break
        candidates = [d for d in sorted(os.listdir(current)) if os.path.isdir(os.path.join(current, d)) and d != "evaluation"]
        if len(candidates) != 1:
            raise FileNotFoundError(
                f"No images/ folder under {current} and cannot pick a unique sub-folder (found {candidates}). "
                "Pass the guidance_scale... folder or the images/ folder explicitly with --images_dir."
            )
        current = os.path.join(current, candidates[0])
    if current != path:
        print(f"Using images from {current}")
    return current


def test_mode_of(images_dir):
    """.../seed_<s>/<test_mode>/<param_string>/<tag>/images -> <test_mode>"""
    for part in reversed(images_dir.split("/")):
        if re.match(r"^(count|position|attribute)_", part):
            return part
    raise ValueError(f"Cannot find a test_mode folder (count_*/position_*/attribute_*) in {images_dir}")


def list_checkpoints(images_dir, checkpoint_filter):
    def step(name):
        return int(name.split("-")[1]) if name.startswith("checkpoint-") else float("inf")

    names = sorted((d for d in os.listdir(images_dir) if os.path.isdir(os.path.join(images_dir, d))), key=step)
    if checkpoint_filter is None:
        return names
    if checkpoint_filter == "best_model":
        wanted = ["best_model"]
    elif checkpoint_filter == "-1":
        wanted = [max((n for n in names if n.startswith("checkpoint-")), key=step, default=None)]
    else:
        wanted = [f"checkpoint-{int(checkpoint_filter)}"]
    missing = [w for w in wanted if w not in names]
    if missing:
        raise FileNotFoundError(f"{missing} not found in {images_dir}; available: {names}")
    return wanted


def parse_label(key, test_mode):
    """prompt_key -> dict(primary=<class idx>, color=<idx or None>, pair=<held-out lookup key>, name=<display label>).

    count/position:               key "K"               -> primary K-1
    count/position composition:   key "COLOR_K"         -> primary K-1, colour idx
    attribute:                    key "COLOR1_COLOR2"   -> primary c1*10+c2
    """
    task = task_of(test_mode)
    parts = key.split("_")
    if task == "attribute":
        c1, c2 = COLOR_NAMES.index(parts[0]), COLOR_NAMES.index(parts[1])
        return dict(primary=c1 * 10 + c2, color=None, pair=(parts[0], parts[1]), name=key)
    k = int(parts[-1])
    color = COLOR_NAMES.index(parts[0]) if len(parts) == 2 else None
    pair = (parts[0], k) if color is not None else None
    return dict(primary=k - 1, color=color, pair=pair, name=key)


class GeneratedImages(Dataset):
    def __init__(self, folder, test_mode, resolution):
        self.items = []
        for f in sorted(os.listdir(folder)):
            m = FILENAME_RE.match(f)
            if m:
                self.items.append((os.path.join(folder, f), parse_label(m.group("key"), test_mode)))
        if not self.items:
            raise FileNotFoundError(f"No prompt_key_*_sample_*.png files in {folder}")
        self.transform = T.Compose([T.Resize((resolution, resolution)), T.ToTensor()])  # same as utils.test_accuracy

    def __len__(self):
        return len(self.items)

    def __getitem__(self, idx):
        path, label = self.items[idx]
        return self.transform(Image.open(path).convert("RGB")), idx


# ---------------------------------------------------------------------------
# metrics
# ---------------------------------------------------------------------------
def summarize(rows, task, has_color, has_shape):
    """rows: list of dicts with pred/target (+ color_pred/color_target, shape_pred, conf, name)."""
    n = len(rows)
    if n == 0:
        return None
    correct = [r["pred"] == r["target"] for r in rows]
    out = {"num_images": n, "accuracy": sum(correct) / n, "confidence": sum(r["conf"] for r in rows) / n}
    if task == "position":
        d = [abs(r["pred"] - r["target"]) for r in rows]
        out["distance"] = sum(min(x, 10 - x) for x in d) / n
    elif task == "count":
        out["distance"] = sum(abs(r["pred"] - r["target"]) for r in rows) / n

    second = None
    if has_color:
        second = [r["color_pred"] == r["color_target"] for r in rows]
        out["color_accuracy"] = sum(second) / n
    if has_shape:
        second = [r["shape_pred"] == 1 for r in rows]  # shape class 1 = ball
        out["shape_accuracy"] = sum(second) / n
    if second is not None:
        out["joint_accuracy"] = sum(a and b for a, b in zip(correct, second)) / n

    per_label = defaultdict(lambda: [0, 0])
    for r, c in zip(rows, correct):
        per_label[r["name"]][0] += c
        per_label[r["name"]][1] += 1
    out["per_label_accuracy"] = {k: v[0] / v[1] for k, v in sorted(per_label.items(), key=lambda kv: str(kv[0]))}
    return out


def confusion(rows, num_classes):
    m = [[0] * num_classes for _ in range(num_classes)]
    for r in rows:
        if 0 <= r["pred"] < num_classes:
            m[r["target"]][r["pred"]] += 1
    return m


@torch.no_grad()
def evaluate_checkpoint(folder, test_mode, primary, secondary, args, device):
    task = task_of(test_mode)
    dataset = GeneratedImages(folder, test_mode, args.resolution)
    loader = DataLoader(dataset, batch_size=args.batch_size, num_workers=args.num_workers)
    has_color = secondary is not None and is_composition(test_mode)
    has_shape = secondary is not None and task == "attribute"

    rows = []
    for images, idx in tqdm.tqdm(loader, desc=os.path.basename(folder), leave=False):
        images = images.to(device)
        logits = primary(images)
        probs = torch.softmax(logits, dim=1)
        pred = probs.argmax(dim=1).tolist()
        conf = probs.max(dim=1).values.tolist()
        pred2 = secondary(images).argmax(dim=1).tolist() if secondary is not None else [None] * len(pred)
        for i, p, c, p2 in zip(idx.tolist(), pred, conf, pred2):
            label = dataset.items[i][1]
            rows.append({
                "pred": p, "target": label["primary"], "conf": c, "name": label["name"], "pair": label["pair"],
                "color_pred": p2 if has_color else None, "color_target": label["color"],
                "shape_pred": p2 if has_shape else None,
            })

    result = {"overall": summarize(rows, task, has_color, has_shape)}
    if is_composition(test_mode):
        ood = held_out_pairs(test_mode)
        result["held_out"] = summarize([r for r in rows if r["pair"] in ood], task, has_color, has_shape)
        result["in_distribution"] = summarize([r for r in rows if r["pair"] not in ood], task, has_color, has_shape)
    num_classes = primary(torch.zeros(1, 3, args.resolution, args.resolution, device=device)).shape[1]
    result["confusion_matrix"] = confusion(rows, num_classes)
    return result


# ---------------------------------------------------------------------------
# reporting
# ---------------------------------------------------------------------------
METRIC_COLUMNS = ["num_images", "accuracy", "confidence", "distance", "color_accuracy", "shape_accuracy", "joint_accuracy"]


def print_table(results):
    splits = [s for s in ("overall", "held_out", "in_distribution") if any(s in r for r in results.values())]
    header = f"{'checkpoint':>18} {'split':>16} " + " ".join(f"{c:>15}" for c in METRIC_COLUMNS)
    print(header)
    print("-" * len(header))
    for ckpt, res in results.items():
        for split in splits:
            s = res.get(split)
            if s is None:
                continue
            cells = [f"{s[c]:15.4f}" if isinstance(s.get(c), float) else f"{s.get(c, ''):>15}" for c in METRIC_COLUMNS]
            print(f"{ckpt:>18} {split:>16} " + " ".join(cells))


def save_results(results, test_mode, images_dir, args):
    out_dir = os.path.join(os.path.dirname(images_dir), "evaluation")
    os.makedirs(out_dir, exist_ok=True)
    base = args.save_name + (f"_{args.checkpoint_filter}" if args.checkpoint_filter else "")

    with open(os.path.join(out_dir, base + ".json"), "w") as f:
        json.dump({"test_mode": test_mode, "images_dir": images_dir, "checkpoints": results}, f, indent=2)

    with open(os.path.join(out_dir, base + ".csv"), "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["checkpoint", "split"] + METRIC_COLUMNS)
        for ckpt, res in results.items():
            for split in ("overall", "held_out", "in_distribution"):
                if res.get(split):
                    writer.writerow([ckpt, split] + [res[split].get(c, "") for c in METRIC_COLUMNS])

    with open(os.path.join(out_dir, base + "_per_label.csv"), "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["checkpoint", "label", "accuracy"])
        for ckpt, res in results.items():
            for label, acc in res["overall"]["per_label_accuracy"].items():
                writer.writerow([ckpt, label, acc])

    for ckpt, res in results.items():
        with open(os.path.join(out_dir, f"{base}_confusion_{ckpt}.csv"), "w", newline="") as f:
            csv.writer(f).writerows(res["confusion_matrix"])
    print(f"\nSaved results to {out_dir}/{base}.json, .csv, _per_label.csv and _confusion_<checkpoint>.csv")


def main():
    args = parse_args()
    images_dir = resolve_images_dir(args.images_dir)
    test_mode = test_mode_of(images_dir)
    device = args.device or ("cuda" if torch.cuda.is_available() else "cpu")
    print(f"test_mode: {test_mode} ({task_of(test_mode)}, composition={is_composition(test_mode)}, complex={is_complex(test_mode)})")

    primary, secondary = load_classifiers(test_mode, device, args.resolution)
    checkpoints = list_checkpoints(images_dir, args.checkpoint_filter)
    print(f"checkpoints: {checkpoints}")

    results = {}
    for ckpt in checkpoints:
        results[ckpt] = evaluate_checkpoint(os.path.join(images_dir, ckpt), test_mode, primary, secondary, args, device)

    print()
    print_table(results)
    if not args.no_save:
        save_results(results, test_mode, images_dir, args)


if __name__ == "__main__":
    main()
